# numpy library & commands practice

In [1]:
# python lists
L= range(1000)
%timeit [i**2 for i in L]


223 µs ± 62.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
import numpy as np  # numpy libraries are lot faster in time and memory consumption wise compared to python lists
n = np.arange(1000)
%timeit n**2


2.54 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
import sys
M = range(2000)
print(sys.getsizeof(2)*len(M)) #memory ocupied by one element times length of the list

56000


In [ ]:
import numpy as np
m = np.arange(2000)
type(m)
print (m.size * m.itemsize) # size of numpy array multiplied by size of the item


16000


In [ ]:
#using arrange function [Numeric Sequence Generators based on step value]

# arange is an array-valued version of the built-in Python range function

type(m)


numpy.ndarray

In [ ]:
a = np.arange(1,20,3) # start, end(exclusive), step
print (a)
a
a.ndim
a.shape # fetch the dimensions of type objects in python


[ 1  4  7 10 13 16 19]


(7,)

In [ ]:
a = np.linspace(100, 400, 4) # start, end, number of points
a


array([100., 200., 300., 400.])

In [ ]:
a = np.ones((3,3))
a

b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.eye(3) # identity matrix i.e. all 1s in diagonal
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
d = np.diag([1,2,3,4]) # extract diagonal
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# rand function by default generates random samples between 0 and 1
# seed ex:42 is randomness fixed in order to pickup same random numbers everytime.

np.random.seed(400)
r = np.random.rand(4)
r

array([0.66872891, 0.22599847, 0.85929874, 0.29039393])

In [ ]:
a = np.random.randn(4) # randn generates numbers between -3 and 3
a

array([-2.350259  ,  0.18329277, -0.31138559, -0.2940661 ])

In [ ]:
# reading from text file using loadtxt

from io import StringIO
import numpy as np

x = StringIO('''23.25 13.45 92.40 90.80
72.3 78.95 92.15 94.30
80.5 99.99 39.23 40.33
''')

d = np.loadtxt(x,delimiter=' ')
print(d)
print(d.ndim, d.shape)



[[23.25 13.45 92.4  90.8 ]
 [72.3  78.95 92.15 94.3 ]
 [80.5  99.99 39.23 40.33]]
2 (3, 4)


In [ ]:
x=2
while x<5:
 print (x)
 x=x+1

2
3
4


In [ ]:
def addnum(a,b):
  x=a+b
  return x

output = addnum(5,8)
print ("sum of nums is ", output)

sum of nums is  13


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
!python --version

Python 3.12.12


In [ ]:
!pwd

/content


In [ ]:
!ls -lrt

total 4
drwxr-xr-x 1 root root 4096 Jan 16 14:24 sample_data


In [ ]:
import agno

In [ ]:
# numpy array
import numpy as np
a = np.array([3,6,8,9])
print(a[2])
print(np.arange(50))


8
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [ ]:
!pip install agno

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 48.5 MB/s eta 0:00:00


In [ ]:
import numpy as np
# randn is generate samples from standard normal distribution or guassian distribution. generates from range -3 to 3 with standard deviation of 1 i.e. -3,-2,-1, 0 , 1, 2, 3. also called as six sigma standard where each deviation is 1 sigma
n = np.random.randn(3,3)
n

array([[ 0.69585082,  1.22758486, -0.36279815],
       [ 0.11254104,  0.39894501,  0.46362158],
       [-0.97688484,  0.13579471,  1.03837311]])

In [ ]:
n = np.random.randint(10,50,2) # 2 integers between 10 and 50
n

array([33, 24])

In [ ]:
b = np.array([True, False])
print(b.dtype)


bool


In [ ]:
#indexing and slicing in arrays. array items can be accessed as python sequences or lists
a = np.arange(10)
print(a)
print(a[5])

[0 1 2 3 4 5 6 7 8 9]
5


In [ ]:
a = np.diag([1,2,3]) # accessing specific array item
print(a)
print(a[1,1])
a


[[1 0 0]
 [0 2 0]
 [0 0 3]]
2


array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 3]])

In [ ]:
a[1,1] = 4 # assigning value to array item
a

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 3]])

In [ ]:
a= np.arange(10)
a[1:8:2] # start index, end index (exclusive), step size of 1

array([1, 3, 5, 7])

In [ ]:
#assignment and slicing
a[5:8] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [ ]:
b = np.arange(5)
print(b)
a[5:] = b[::-1] #assigning and b[::-1] is [4 3 2 1 0] and a[5: ] replaces with reverse of b i.e. 0 1 2 3 4 in place of 5 to 10 in array a
a

[0 1 2 3 4]


array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [ ]:
#reshaping numpy array i.e convert row/coumn data of an image pixel to single shape array to feed into AI model to identify the image
import numpy as np
np.random.seed(100)
x=np.random.randint(10,100,8)
print(x,end='\n\n')


[18 34 77 97 89 58 20 62]



In [ ]:
y = x.reshape(2,4)
print(y)
y = x.reshape(2,2,2)
print(y)

[[18 34 77 97]
 [89 58 20 62]]
[[[18 34]
  [77 97]]

 [[89 58]
  [20 62]]]


In [ ]:
#hstack and vstack are where 2 or more arrays are joined horizantaly or vertically

x=np.array([[-1,1], [-3,3]])
y=np.array([[-2,2], [-4,4]])
np.vstack((x,y))
np.hstack((x,y))

z=np.array([[-5,5,5],[-6,6,6]])
np.hstack((x,y,z))

array([[-1,  1, -2,  2, -5,  5,  5],
       [-3,  3, -4,  4, -6,  6,  6]])

In [ ]:

#copying
a=np.arange(10)
a # stored in physical memory
b= a[::2]
b # refers to same a physical memory location
np.shares_memory(a,b)
b[0]=10
b # if b modified then a value modified too
#thats when copy is used to not replace values




array([10,  2,  4,  6,  8])

In [ ]:
#fancy indexing
#numpy arrays can be indexed with slices but also with boolean or int arrays (masks). it creates copies not views

a = np.random.randint(0,30,10)
a


array([ 8, 21,  5,  6, 28, 17,  2,  1, 22, 16])

In [ ]:
mask = (a % 2 == 0)
extract_from_a = a[mask] # this is even number masking
extract_from_a

array([ 8,  6, 28,  2, 22, 16])

In [ ]:
a[mask] = -3 # indexing with mask is useful to assign new value to sub array
a


array([-3, 21,  5, -3, -3, 17, -3,  1, -3, -3])

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
a+3


array([4, 5, 6, 7])

In [ ]:
a**3

array([ 1,  8, 27, 64])

In [ ]:
b=np.ones(4) + 1 # b = [1 1 1 1] + 1 i.e. b= [2 2 2 2]
a - b # a-b = 1-2, 2-2, 3-2, 4-3 where a = [1 2 3 4]

array([-1.,  0.,  1.,  2.])

In [ ]:
a * b

array([2., 4., 6., 8.])

In [ ]:
c = np.diag([1,2,3,4]) # matrix multiplication where rows multiply by columns in matrix
print (c*c)

print(c.dot(c))



[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [ ]:
# comaprisons
a = np.array([1,2,3,4])
b = np.array([2,2,5,4])
a>b
a==b
np.array_equal(a,c)

False

In [ ]:
a = np.array([1,1,0,0])
b = np.array([1,0,1,0])
np.logical_or(a,b) # logical OR operator
np.logical_and(a,b) # logical AND operator

array([ True, False, False, False])

In [ ]:
#transcendental functions
a=np.arange(5)
np.sin(a) # gives sin of that value



array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.log(a)

/tmp/ipython-input-176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
#compute sums
x=np.array([1,2,3,4,5])
np.sum(x)

np.int64(15)

In [ ]:
x=np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
x=np.array([1,2,3,4])
x.min() # minimum element
x.argmin() # index of min element
x.argmax() #index of max element

np.int64(3)

In [ ]:
# statistical functions
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean()
np.median(x)
x.std()


np.float64(0.82915619758885)

In [ ]:
np.median(y,axis=-1) # last axis
np.median(y,axis=0) # first axis
np.median(y,axis=1) # second axis


array([2., 5.])

In [ ]:
#array shape manipulation
a=np.array([[1,2,3],[4,5,6]])  #combine all array items into 1 array
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.T # transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [ ]:
print(a.shape)
print(a)


(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
b=a.ravel()
print(b)

[1 2 3 4 5 6]


In [ ]:
b=b.reshape((3,2)) #reshape changes the matrix shape i.e. rows and columns
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#sorting
a=np.array([[5,4,6],[2,3,3]])
b=np.sort(a,axis=1)
b

a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 3, 3]])

In [ ]:
a=np.array([4,3,2,1,2])
c=np.argsort(a) # index element sorting
c


array([3, 2, 4, 1, 0])